name: Gradle7

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: ['11', '17']
        distribution: ['temurin']
        gradle: ['7.5.1']
      fail-fast: false
    name: JAVA ${{ matrix.java }} OS ${{ matrix.os }} Gradle ${{ matrix.gradle }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10

      - name: Install build-tools 34.0.0, platformtools and platform android-34
        run: sdkmanager --install "build-tools;34.0.0" "platform-tools" "platforms;android-34"

      - name: Build with Gradle
        run: |
           ./gradlew wrapper --gradle-version=${{ matrix.gradle }}
           ./gradlew clean build --stacktrace

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: groestlcoin-wallet-JAVA${{ matrix.java }}-${{ matrix.os }}-${{ matrix.gradle }}
          path: |
            wallet/build/outputs/apk/

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: groestlcoin-wallet-JAVA${{ matrix.java }}-${{ matrix.os }}-${{ matrix.gradle }}
