name: Gradle6

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        java: ['11']
        distribution: ['temurin']
        gradle: ['6.7.1']
      fail-fast: false
    name: JAVA ${{ matrix.java }} OS ${{ matrix.os }} Gradle ${{ matrix.gradle }}
    steps:
      - uses: actions/checkout@v3

      - name: Downgrade Android plugin from 7.4.1 to 4.2.0
        run:  sed -i -e "s|7.4.1|4.2.0|g" build.gradle

      - name: Downgrade DistributionUrl from Gradle 7.5.1 to Gradle 6.7.1
        run:  sed -i -e "s|7.5.1|6.7.1|g" gradle/wrapper/gradle-wrapper.properties

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10

      - name: Install build-tools 33.0.2, platformtools and platform android-33
        run: sdkmanager --install "build-tools;33.0.2" "platform-tools" "platforms;android-33"

      - name: Fix build tools 33.0.2 issue
        run: |
           ln -s ${ANDROID_HOME}/build-tools/33.0.2/d8 ${ANDROID_HOME}/build-tools/33.0.2/dx
           ln -s ${ANDROID_HOME}/build-tools/33.0.2/lib/d8.jar ${ANDROID_HOME}/build-tools/33.0.2/lib/dx.jar

      - name: Build with Gradle
        run: |
           ./gradlew wrapper --gradle-version=${{ matrix.gradle }}
           ./gradlew clean build --stacktrace

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: groestlcoin-wallet-JAVA${{ matrix.java }}-${{ matrix.os }}-${{ matrix.gradle }}
          path: |
            wallet/build/outputs/apk/

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: groestlcoin-wallet-JAVA${{ matrix.java }}-${{ matrix.os }}-${{ matrix.gradle }}
