name: Gradle7

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: ['11', '17']
        distribution: ['temurin']
        gradle: ['7.4.2']
      fail-fast: false
    name: JAVA ${{ matrix.java }} OS ${{ matrix.os }} Gradle ${{ matrix.gradle }}
    steps:
      - uses: actions/checkout@v1

      - run:  sed -i -e "s|7.2.0|7.2.1|g" build.gradle

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build with Gradle
        run: |
           ./gradlew wrapper --gradle-version=${{ matrix.gradle }}
           ./gradlew wrapper --gradle-version=${{ matrix.gradle }}
           ./gradlew clean build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: groestlcoin-wallet-JAVA${{ matrix.java }}-${{ matrix.os }}-${{ matrix.gradle }}
          path: |
            wallet/build/outputs/apk/

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: groestlcoin-wallet-JAVA${{ matrix.java }}-${{ matrix.os }}-${{ matrix.gradle }}
